spring.application.name=spring-with-ai
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n

spring.ai.model.chat=ollama
spring.ai.model.chat.url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2
